version: '2'
services:
  back:
    image: tastify/api
    build:
      context: .
      dockerfile: docker/back.dockerfile
    environment:
      DB_URL: "postgresql+asyncpg://postgres@db:5432/postgres"
    depends_on:
      - db
    ports:
      - "8000:8000"
    expose:
      - "8000"

  db:
    image: postgres:15
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    expose:
      - "5432"
