name: Deploy to Remote

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd tastify
            git fetch --depth=1 origin ${{ github.sha }}
            git reset --hard ${{ github.sha }}
            docker compose --file ./docker/remote.docker-compose.yaml stop
            docker container prune -f
            docker volume prune -f
            docker compose --file ./docker/remote.docker-compose.yaml up --build -d || {
              docker compose --file ./docker/remote.docker-compose.yaml logs --tail=50 migrate
              exit 1
            }

